version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"   # Porta padrão AMQP
      - "15672:15672" # Porta para o Management Plugin (UI: http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

  pedidos:
    build:
      context: .
      dockerfile: ./pedidos/Dockerfile
    container_name: microsservico-pedidos
    ports:
      - "8081:8081"
    environment:
      SPRING_RABBITMQ_ADDRESSES: amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

  produtos:
    build:
      context: .
      dockerfile: ./estoque/Dockerfile
    container_name: microsservico-produtos
    ports:
      - "8082:8082"
    environment:
      SPRING_RABBITMQ_ADDRESSES: amqp://user:password@rabbitmq:5672
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge